repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# hadolint
- repo: https://github.com/hadolint/hadolint.git
   rev: v2.12.0
   hooks:
      - id: hadolint-docker
         entry: hadolint/hadolint:v2.12.0 hadolint
         