FROM ruby:2.2-alpine

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

WORKDIR /app

ADD . /app

RUN apk --no-cache --update add build-base \
    && bundle install \
    && apk del build-base \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["puma"]

