FROM ruby:2.2-alpine

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

WORKDIR /app

COPY . .

RUN apk --no-cache --update add build-base \
    && bundle install \
    && apk del build-base

CMD ["puma"]
