version: '3.3'
services:
  
  post_db:
    env_file:
      - .env    
    image: mongo:3.2
    container_name: mongo_db
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
    
  ui:
    env_file:
      - .env
    build: ./ui
    image: ${MY_USER}/ui:${UI_VERSION}
    container_name: ui
    ports:
      - ${LOCAL_PORT}:${REMOTE_PORT}/tcp
    networks:
      - front_net
      
  post:
    env_file:
      - .env
    build: ./post-py
    image: ${MY_USER}/post:${POST_VERSION}
    container_name: post
    networks:
      - front_net
      - back_net
    
  comment:
    env_file:
      - .env
    build: ./comment  
    image: ${MY_USER}/comment:${COMMENT_VERSION}
    container_name: comment
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24

